title: Jaeho Lee
description: Jaeho Lee — founder, reader, and writer in New York City.
url: "https://jaeho.org"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - redline
  - "Untitled.md"
  - "Untitled 1.md"
