title: Jaeho Lee
description: Jaeho Lee’s personal corner of the internet—notes on work, life, and ideas worth keeping.
url: "https://jaeho.org"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - redline
  - "Untitled.md"
  - "Untitled 1.md"
