title: Jaeho Lee
description: Personal site and blog
url: "" # Your custom domain, e.g. https://jaeho.com
baseurl: "" # Leave empty if deploying to root

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
